version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: root
      
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: root
      
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: root
      
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120
      runas: root